<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit23cead6d4910cb15c9f0fbd30a8b12db
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'ReCaptcha\\' => 10,
        ),
        'P' => 
        array (
            'Parse\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ReCaptcha\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha',
        ),
        'Parse\\' => 
        array (
            0 => __DIR__ . '/..' . '/parse/php-sdk/src/Parse',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit23cead6d4910cb15c9f0fbd30a8b12db::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit23cead6d4910cb15c9f0fbd30a8b12db::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
